package com.nullcognition.storio.sqlite.entity;
// ersin 09/11/15 Copyright (c) 2015+ All rights reserved.

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.nullcognition.storio.sqlite.table.ModelTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

@StorIOSQLiteType(table = ModelTable.TABLE)
public class Model{

	@Nullable
	@StorIOSQLiteColumn(name = ModelTable.COLUMN_ID, key = true)
	Long id;

	@NonNull
	@StorIOSQLiteColumn(name = ModelTable.COLUMN_AUTHOR)
	String author;

	@NonNull
	@StorIOSQLiteColumn(name = ModelTable.COLUMN_CONTENT)
	String content;

	// leave default constructor for AutoGenerated code!
	Model(){ }

	private Model(@Nullable Long id, @NonNull String author, @NonNull String content){
		this.id = id;
		this.author = author;
		this.content = content;
	}

	@NonNull
	public static Model newModel(@Nullable Long id, @NonNull String author, @NonNull String content){
		return new Model(id, author, content);
	}

	@NonNull
	public static Model newModel(@NonNull String author, @NonNull String content){
		return new Model(null, author, content);
	}

	@Nullable
	public Long id(){
		return id;
	}

	@NonNull
	public String author(){
		return author;
	}

	@NonNull
	public String content(){
		return content;
	}

	// BTW, you can use AutoValue/AutoParcel to get immutability and code generation for free
	@Override
	public boolean equals(Object o){
		if(this == o){ return true; }
		if(o == null || getClass() != o.getClass()){ return false; }

		Model model = (Model) o;

		if(id != null ? !id.equals(model.id) : model.id != null){ return false; }
		if(!author.equals(model.author)){ return false; }
		return content.equals(model.content);
	}

	@Override
	public int hashCode(){
		int result = id != null ? id.hashCode() : 0;
		result = 31 * result + author.hashCode();
		result = 31 * result + content.hashCode();
		return result;
	}

	@Override
	public String toString(){
		return "Model{" +
				"id=" + id +
				", author='" + author + '\'' +
				", content='" + content + '\'' +
				'}';
	}
}
