package com.nullcognition.storio.content_resolver.entity;
// ersin 10/11/15 Copyright (c) 2015+ All rights reserved.


import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.nullcognition.storio.content_resolver.table.CRModelTable;
import com.nullcognition.storio.sqlite.table.ModelTable;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

@StorIOSQLiteType(table = CRModelTable.TABLE)
public class CRModel{

	@Nullable
	@StorIOSQLiteColumn(name = ModelTable.COLUMN_ID, key = true)
	Long id;

	@NonNull
	@StorIOSQLiteColumn(name = ModelTable.COLUMN_CONTENT)
	String content;

	// leave default constructor for AutoGenerated code!
	CRModel(){ }

	private CRModel(@Nullable Long id, @NonNull String content){
		this.id = id;
		this.content = content;
	}

	@NonNull
	public static CRModel newModel(@Nullable Long id, @NonNull String content){
		return new CRModel(id, content);
	}

	@NonNull
	public static CRModel newModel(@NonNull String content){
		return new CRModel(null, content);
	}

	@Nullable
	public Long id(){
		return id;
	}

	@NonNull
	public String content(){
		return content;
	}

	// BTW, you can use AutoValue/AutoParcel to get immutability and code generation for free
	@Override
	public boolean equals(Object o){
		if(this == o){ return true; }
		if(o == null || getClass() != o.getClass()){ return false; }

		CRModel model = (CRModel) o;

		if(id != null ? !id.equals(model.id) : model.id != null){ return false; }
		return content.equals(model.content);
	}

	@Override
	public int hashCode(){
		int result = id != null ? id.hashCode() : 0;
		result = 31 * result + content.hashCode();
		return result;
	}

	@Override
	public String toString(){
		return "Model{" +
				"id=" + id +
				", content='" + content + '\'' +
				'}';
	}
}
